language: node_js
node_js:
  - "6"
services:
  - mysql
before_script:
  - mysql -e 'create database myapp_test;'
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root